services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: dofimall-backend
    restart: always
    env_file: ./backend/.env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/dofimall_sniper.db
    volumes:
      - ./backend/screenshots:/app/screenshots
      - ./backend/logs:/app/logs
      - db-data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dofimall

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: dofimall-frontend
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    environment:
      - VIRTUAL_HOST=dofisniper.odubasolar.com
      - LETSENCRYPT_HOST=dofisniper.odubasolar.com
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dofimall

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: always
    networks:
      dofimall:
        aliases:
          - proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    environment:
      - DEFAULT_EMAIL=admin@odubasolar.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - acme:/etc/acme.sh:rw
    depends_on:
      - proxy
    restart: always
    networks:
      - dofimall

volumes:
  db-data:
  certs:
  vhost:
  html:
  acme:

networks:
  dofimall:
    driver: bridge
